title: robinlennox.github.io
lang: en

remote_theme: rundocs/jekyll-rtd-theme

addons_branch: true
edit: true

addons:
  - github
  - i18n
  - plugins
  - analytics

copyright:
  since: false
  revision: false

readme_index:
  with_frontmatter: true

scss: |
  .content-wrap .wy-nav-content{max-width:75%}

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - jekyll-rtd-theme.gemspec
  - example
