title: robinlennox.github.io
lang: en

remote_theme: rundocs/jekyll-rtd-theme

addons_branch: true
edit: true

addons:
  - github
  - i18n
  - plugins
  - analytics

copyright:
  since: false
  revision: false

readme_index:
  with_frontmatter: true
  
script: |
  alert("it");
  alert("works!");

scss: |
  .wy-nav-content-wrap{background:#fcfcfc}
  .wy-nav-content-wrap .wy-nav-content{max-width:none}
  .wy-nav-content-wrap .wy-nav-content{min-width:none}
  .wy-nav-content { max-width: 1200px !important;}

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - jekyll-rtd-theme.gemspec
  - example
